In [1]:
import numpy as np

A = np.zeros((5,5))
for i in range (0,5):
    for j in range (0,5):
        A[i,j]=(i+1)**(4-j)
        
detA = np.linalg.det(A)
B = A.copy()
C = [1,0,0,0,3]
B[:, 0] =  C   #replace first column in A with C

print(f'A = {A}')
print(f'C = {B}')

A = [[  1.   1.   1.   1.   1.]
 [ 16.   8.   4.   2.   1.]
 [ 81.  27.   9.   3.   1.]
 [256.  64.  16.   4.   1.]
 [625. 125.  25.   5.   1.]]
C = [[  1.   1.   1.   1.   1.]
 [  0.   8.   4.   2.   1.]
 [  0.  27.   9.   3.   1.]
 [  0.  64.  16.   4.   1.]
 [  3. 125.  25.   5.   1.]]
