In [7]:
import numpy as np
from numpy.linalg import *

A = np.array([[-2,-3,2],[4,5,-2],[3,3,-1]])

lam = np.linalg.eigvals(A)

Eig, P = np.linalg.eig(A)

u1 = P[:,0] #0 for column index, and ":" for all the rows at index 0 
u2 = p[:,1]
u2 = p[:,2]




[[-5.77350269e-01 -4.08248290e-01  7.07106781e-01]
 [ 5.77350269e-01  8.16496581e-01 -7.07106781e-01]
 [ 5.77350269e-01  4.08248290e-01 -8.85103622e-16]]
[-1.  2.  1.]
